/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FormulasRouteImport } from './routes/formulas'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LawsIndexRouteImport } from './routes/laws.index'
import { Route as LabIndexRouteImport } from './routes/lab.index'
import { Route as LawsSlugRouteImport } from './routes/laws.$slug'
import { Route as LabSlugRouteImport } from './routes/lab.$slug'

const FormulasRoute = FormulasRouteImport.update({
  id: '/formulas',
  path: '/formulas',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LawsIndexRoute = LawsIndexRouteImport.update({
  id: '/laws/',
  path: '/laws/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabIndexRoute = LabIndexRouteImport.update({
  id: '/lab/',
  path: '/lab/',
  getParentRoute: () => rootRouteImport,
} as any)
const LawsSlugRoute = LawsSlugRouteImport.update({
  id: '/laws/$slug',
  path: '/laws/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LabSlugRoute = LabSlugRouteImport.update({
  id: '/lab/$slug',
  path: '/lab/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/formulas': typeof FormulasRoute
  '/lab/$slug': typeof LabSlugRoute
  '/laws/$slug': typeof LawsSlugRoute
  '/lab/': typeof LabIndexRoute
  '/laws/': typeof LawsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/formulas': typeof FormulasRoute
  '/lab/$slug': typeof LabSlugRoute
  '/laws/$slug': typeof LawsSlugRoute
  '/lab': typeof LabIndexRoute
  '/laws': typeof LawsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/formulas': typeof FormulasRoute
  '/lab/$slug': typeof LabSlugRoute
  '/laws/$slug': typeof LawsSlugRoute
  '/lab/': typeof LabIndexRoute
  '/laws/': typeof LawsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/favorites'
    | '/formulas'
    | '/lab/$slug'
    | '/laws/$slug'
    | '/lab/'
    | '/laws/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/favorites'
    | '/formulas'
    | '/lab/$slug'
    | '/laws/$slug'
    | '/lab'
    | '/laws'
  id:
    | '__root__'
    | '/'
    | '/favorites'
    | '/formulas'
    | '/lab/$slug'
    | '/laws/$slug'
    | '/lab/'
    | '/laws/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FavoritesRoute: typeof FavoritesRoute
  FormulasRoute: typeof FormulasRoute
  LabSlugRoute: typeof LabSlugRoute
  LawsSlugRoute: typeof LawsSlugRoute
  LabIndexRoute: typeof LabIndexRoute
  LawsIndexRoute: typeof LawsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/formulas': {
      id: '/formulas'
      path: '/formulas'
      fullPath: '/formulas'
      preLoaderRoute: typeof FormulasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laws/': {
      id: '/laws/'
      path: '/laws'
      fullPath: '/laws/'
      preLoaderRoute: typeof LawsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/': {
      id: '/lab/'
      path: '/lab'
      fullPath: '/lab/'
      preLoaderRoute: typeof LabIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laws/$slug': {
      id: '/laws/$slug'
      path: '/laws/$slug'
      fullPath: '/laws/$slug'
      preLoaderRoute: typeof LawsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/$slug': {
      id: '/lab/$slug'
      path: '/lab/$slug'
      fullPath: '/lab/$slug'
      preLoaderRoute: typeof LabSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FavoritesRoute: FavoritesRoute,
  FormulasRoute: FormulasRoute,
  LabSlugRoute: LabSlugRoute,
  LawsSlugRoute: LawsSlugRoute,
  LabIndexRoute: LabIndexRoute,
  LawsIndexRoute: LawsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
